"""
defectpl.participation_ratio
============================

Electronic-state participation ratio (P-ratio) and inverse participation
ratio (IPR) computed from VASP PROCAR data for defect supercell calculations.

Physical background
-------------------
For a Kohn-Sham state |ψ_{n,k,σ}⟩ the site-projected wavefunction character
of atom *i* is

    p_i(n,k,σ) = Σ_lm  |⟨Y^i_lm | ψ_{n,k,σ}⟩|²

which is exactly the "tot" column per atom stored in a VASP PROCAR file.

**P-ratio** (pydefect convention)
    Fraction of the total wavefunction weight residing on the *neighbouring*
    atoms of the defect:

        P-ratio = Σ_{i ∈ N} p_i / Σ_i p_i

    * 0.0 → fully delocalized (bulk host state)
    * 1.0 → entirely concentrated on defect neighbours (deep defect level)

**IPR** (inverse participation ratio, site-based)
    A code-agnostic localization metric:

        IPR = Σ_i p_i² / (Σ_i p_i)²

    * 1/N_atoms → perfectly delocalized
    * 1.0       → fully localized on one atom

Both quantities are stored for every (spin, k-point, band) triplet.

Required input files
--------------------
PROCAR
    VASP projected wavefunction output.  Requires ``LORBIT = 11`` or ``12``
    in INCAR.

defect_entry.json
    Provides ``defect_name`` and ``defect_center`` (fractional coordinates).
    Can be generated by ``defectpl pr make-entry`` without any external tools.

Optional but recommended
~~~~~~~~~~~~~~~~~~~~~~~~
defect_structure_info.json
    Contains the neighbour atom index list used for the P-ratio numerator.
    Can be generated by ``defectpl pr make-dsi``.
    When absent the module falls back to a distance-based search using
    POSCAR/CONTCAR.

POSCAR / CONTCAR
    Only required for the distance-based neighbour fallback.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Public type aliases
# ---------------------------------------------------------------------------
PRatioData = Dict[str, Dict[str, Dict[str, dict]]]
"""Nested dict keyed [spin_label][kpt_label][band_label] → metric dict."""


# ---------------------------------------------------------------------------
# Native PROCAR parser (no pymatgen required)
# ---------------------------------------------------------------------------


def _parse_procar_native(procar_path: Path) -> dict:
    """
    Parse a VASP PROCAR file using pure Python (no pymatgen).

    Supports both non-spin-polarised (ISPIN=1) and spin-polarised (ISPIN=2)
    calculations with any orbital decomposition (LORBIT 10, 11, or 12).

    Parameters
    ----------
    procar_path : Path

    Returns
    -------
    dict  — same schema as :func:`read_procar`.

    Notes
    -----
    Only the ``tot`` column (sum over all angular-momentum channels) is read
    per ion; the individual s/p/d/f columns are discarded.
    """
    procar_path = Path(procar_path)
    if not procar_path.exists():
        raise FileNotFoundError(f"PROCAR not found: {procar_path}")

    with open(procar_path, "r", encoding="utf-8", errors="ignore") as fh:
        lines = fh.readlines()

    # ── header ──────────────────────────────────────────────────────────────
    header = lines[0].upper()
    is_spin2 = "ISPIN" in header and "2" in header

    # Find the dimension line "# of k-points:  N  # of bands:  M  # of ions:  P"
    dim_pat = re.compile(
        r"#\s*of\s+k-points:\s*(\d+)\s+#\s*of\s+bands:\s*(\d+)\s+#\s*of\s+ions:\s*(\d+)",
        re.IGNORECASE,
    )
    n_kpoints = n_bands = n_ions = None
    first_dim_line = None
    for idx, line in enumerate(lines):
        m = dim_pat.search(line)
        if m:
            n_kpoints = int(m.group(1))
            n_bands = int(m.group(2))
            n_ions = int(m.group(3))
            first_dim_line = idx
            break

    if n_kpoints is None:
        raise ValueError(f"Could not parse dimensions from {procar_path}")

    # ── regex patterns ───────────────────────────────────────────────────────
    kpt_pat = re.compile(
        r"k-point\s+\d+\s*:\s*([\d.\-+Ee]+)\s+([\d.\-+Ee]+)\s+([\d.\-+Ee]+)"
    )
    wgt_pat = re.compile(r"weight\s*=\s*([\d.\-+Ee]+)")
    band_pat = re.compile(
        r"band\s+\d+\s*#\s*energy\s+([\d.\-+Ee]+)\s*#\s*occ\.\s*([\d.\-+Ee]+)"
    )
    ion_pat = re.compile(r"^\s+\d+\s+")  # line starts with an ion index

    # ── storage ─────────────────────────────────────────────────────────────
    n_spins = 2 if is_spin2 else 1

    # shape: (n_spins, n_kpoints, n_bands, n_ions)
    site_proj = np.zeros((n_spins, n_kpoints, n_bands, n_ions), dtype=np.float64)
    eigenvalues = np.zeros((n_spins, n_kpoints, n_bands), dtype=np.float64)
    occupancies = np.zeros((n_spins, n_kpoints, n_bands), dtype=np.float64)
    kpoints_arr = np.zeros((n_kpoints, 3), dtype=np.float64)
    weights_arr = np.zeros(n_kpoints, dtype=np.float64)

    spin_idx = 0
    k_idx = -1
    b_idx = -1
    i_idx = -1
    header_seen = False  # ion-column header line

    for line in lines[first_dim_line + 1 :]:
        stripped = line.strip()
        if not stripped:
            continue

        # New spin block detected by a repeated dimension line
        if dim_pat.search(line):
            spin_idx += 1
            k_idx = -1
            b_idx = -1
            continue

        # k-point line
        m = kpt_pat.search(line)
        if m:
            k_idx += 1
            if spin_idx == 0:
                kpoints_arr[k_idx] = [
                    float(m.group(1)),
                    float(m.group(2)),
                    float(m.group(3)),
                ]
                mw = wgt_pat.search(line)
                if mw:
                    weights_arr[k_idx] = float(mw.group(1))
            b_idx = -1
            header_seen = False
            continue

        # Band line
        m = band_pat.search(line)
        if m:
            b_idx += 1
            i_idx = -1
            header_seen = False
            si = min(spin_idx, n_spins - 1)
            ki = min(k_idx, n_kpoints - 1)
            eigenvalues[si, ki, b_idx] = float(m.group(1))
            occupancies[si, ki, b_idx] = float(m.group(2))
            continue

        # Ion-column header (skip it)
        if stripped.startswith("ion") and "tot" in stripped:
            header_seen = True
            continue

        # "tot" summary line (skip)
        if stripped.startswith("tot"):
            continue

        # Ion data line
        if header_seen and ion_pat.match(line):
            tokens = stripped.split()
            try:
                i_idx += 1
                if i_idx < n_ions:
                    # Last token is "tot"
                    tot_val = float(tokens[-1])
                    si = min(spin_idx, n_spins - 1)
                    ki = min(k_idx, n_kpoints - 1)
                    site_proj[si, ki, b_idx, i_idx] = tot_val
            except (ValueError, IndexError):
                pass

    # ── pack into output dict ────────────────────────────────────────────────
    # Use sentinel spin objects that mimic pymatgen's Spin enum (hashable ints)
    class _Spin(int):
        def __repr__(self):
            return "Spin.up" if self == 1 else "Spin.down"

    _up = _Spin(1)
    _down = _Spin(-1)

    spins = [_up] if n_spins == 1 else [_up, _down]

    sp_proj = {_up: site_proj[0]}
    sp_eigs = {_up: eigenvalues[0]}
    sp_occ = {_up: occupancies[0]}
    if n_spins == 2:
        sp_proj[_down] = site_proj[1]
        sp_eigs[_down] = eigenvalues[1]
        sp_occ[_down] = occupancies[1]

    return {
        "n_kpoints": n_kpoints,
        "n_bands": n_bands,
        "n_ions": n_ions,
        "n_spins": n_spins,
        "spins": spins,
        "site_proj": sp_proj,
        "eigenvalues": sp_eigs,
        "occupancies": sp_occ,
        "kpoints": kpoints_arr,
        "weights": weights_arr,
    }


# ---------------------------------------------------------------------------
# PROCAR reader (pymatgen primary, native fallback)
# ---------------------------------------------------------------------------


def read_procar(procar_path: str | Path, use_pymatgen: bool = True) -> dict:
    """
    Parse a VASP PROCAR file and return projection arrays.

    Tries pymatgen's ``Procar`` class first (if available and
    ``use_pymatgen=True``); falls back to the built-in native parser.

    Parameters
    ----------
    procar_path : str or Path
        Path to the PROCAR file.
    use_pymatgen : bool, optional
        Attempt to use pymatgen's parser first.  Set to ``False`` to force
        the native parser.  Default: ``True``.

    Returns
    -------
    dict with keys:

    ``n_kpoints`` : int
    ``n_bands``   : int
    ``n_ions``    : int
    ``n_spins``   : int
    ``spins``     : list of spin sentinels
    ``site_proj`` : dict[spin, np.ndarray shape (nk, nb, ni)]
        Site-projected weight summed over all orbital channels.
    ``eigenvalues`` : dict[spin, np.ndarray shape (nk, nb)]
    ``occupancies`` : dict[spin, np.ndarray shape (nk, nb)]
    ``kpoints``   : np.ndarray shape (nk, 3)
    ``weights``   : np.ndarray shape (nk,)

    Raises
    ------
    FileNotFoundError
        If the PROCAR file does not exist.
    """
    procar_path = Path(procar_path)
    if not procar_path.exists():
        raise FileNotFoundError(f"PROCAR not found: {procar_path}")

    if use_pymatgen:
        try:
            from pymatgen.io.vasp.outputs import Procar

            logger.info("Parsing PROCAR with pymatgen: %s", procar_path)
            p = Procar(str(procar_path))

            spins = list(p.data.keys())
            data_arr = p.data[spins[0]]  # (nk, nb, ni, n_orb)
            n_kpoints, n_bands, n_ions, _ = data_arr.shape

            site_proj = {spin: arr.sum(axis=-1) for spin, arr in p.data.items()}

            return {
                "n_kpoints": n_kpoints,
                "n_bands": n_bands,
                "n_ions": n_ions,
                "n_spins": len(spins),
                "spins": spins,
                "site_proj": site_proj,
                "eigenvalues": getattr(p, "eigenvalues", None),
                "occupancies": getattr(p, "occupancies", None),
                "kpoints": np.array(p.kpoints)
                if getattr(p, "kpoints", None) is not None
                else None,
                "weights": np.array(p.weights)
                if getattr(p, "weights", None) is not None
                else None,
            }
        except Exception as exc:
            logger.warning(
                "pymatgen Procar failed (%s); falling back to native parser.", exc
            )

    logger.info("Parsing PROCAR natively: %s", procar_path)
    return _parse_procar_native(procar_path)


# ---------------------------------------------------------------------------
# Neighbour detection helpers
# ---------------------------------------------------------------------------


def neighbors_from_defect_structure_info(dsi_path: str | Path) -> Optional[List[int]]:
    """
    Extract neighbour atom indices from a ``defect_structure_info.json`` file.

    The function tries all key names used across known pydefect versions.

    Parameters
    ----------
    dsi_path : str or Path

    Returns
    -------
    list of int (0-based POSCAR order) or None if not found / parse error.
    """
    dsi_path = Path(dsi_path)
    if not dsi_path.exists():
        return None
    try:
        with open(dsi_path) as fh:
            dsi = json.load(fh)
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Could not read %s: %s", dsi_path, exc)
        return None

    for key in (
        "neighbor_atom_indices",
        "neighboring_atom_indices",
        "neighboring_sites",
        "neighbor_sites",
    ):
        if key in dsi:
            val = dsi[key]
            if val and isinstance(val[0], dict):
                return [int(v["index"]) for v in val]
            return [int(v) for v in val]

    # Fallback: look for a 'neighbors' list of dicts that carry an 'index'
    if "neighbors" in dsi:
        entries = dsi["neighbors"]
        if entries and isinstance(entries[0], dict) and "index" in entries[0]:
            return [int(e["index"]) for e in entries]

    return None


def neighbors_from_structure(
    poscar_path: str | Path,
    defect_center_frac: Sequence[float],
    cutoff_radius: float = 3.5,
) -> List[int]:
    """
    Distance-based fallback neighbour search.

    Finds all atom indices within *cutoff_radius* Å of *defect_center_frac*
    (fractional coordinates) using the minimum-image convention.

    Parameters
    ----------
    poscar_path : str or Path
    defect_center_frac : sequence of 3 floats
    cutoff_radius : float, optional (Å, default 3.5)

    Returns
    -------
    list of int
    """
    from pymatgen.core import Structure

    struct = Structure.from_file(str(poscar_path))
    center = np.array(defect_center_frac, dtype=float)
    neighbors: List[int] = []
    for i, site in enumerate(struct):
        diff = center - site.frac_coords
        diff -= np.round(diff)  # minimum image
        d = np.linalg.norm(struct.lattice.get_cartesian_coords(diff))
        if d < cutoff_radius:
            neighbors.append(i)
    logger.debug(
        "Found %d neighbours within %.2f Å of defect centre",
        len(neighbors),
        cutoff_radius,
    )
    return neighbors


def resolve_neighbors(
    dsi_path: Optional[str | Path],
    poscar_path: Optional[str | Path],
    defect_center_frac: Sequence[float],
    cutoff_radius: float = 3.5,
) -> Tuple[List[int], str]:
    """
    Resolve neighbour atom indices using the best available source.

    Priority:
    1. ``defect_structure_info.json`` (authoritative source)
    2. Distance-based search on POSCAR/CONTCAR
    3. Empty list (no neighbour info; P-ratio will be 0 for all states)

    Parameters
    ----------
    dsi_path : path or None
    poscar_path : path or None
    defect_center_frac : sequence of 3 floats
    cutoff_radius : float (Å)

    Returns
    -------
    (indices, source_description)
    """
    if dsi_path is not None:
        indices = neighbors_from_defect_structure_info(dsi_path)
        if indices is not None:
            return indices, f"defect_structure_info.json ({len(indices)} atoms)"

    if poscar_path is not None and Path(poscar_path).exists():
        try:
            indices = neighbors_from_structure(
                poscar_path, defect_center_frac, cutoff_radius
            )
            return (
                indices,
                f"distance search r<{cutoff_radius:.1f}Å ({len(indices)} atoms)",
            )
        except Exception as exc:
            logger.warning("Distance-based neighbour search failed: %s", exc)

    logger.warning("No neighbour information found; P-ratio will be 0 for all states.")
    return [], "none (P-ratio will be 0)"


# ---------------------------------------------------------------------------
# Core calculation
# ---------------------------------------------------------------------------


def compute_participation_ratios(
    procar_data: dict,
    neighbor_indices: Sequence[int],
    defect_name: str = "unknown",
    defect_center: Sequence[float] = (0.5, 0.5, 0.5),
) -> dict:
    """
    Compute P-ratio and IPR for every (spin, k-point, band) triplet.

    Parameters
    ----------
    procar_data : dict
        As returned by :func:`read_procar`.
    neighbor_indices : sequence of int
        0-based atom indices that constitute the defect neighbourhood.
        Used in the P-ratio numerator.
    defect_name : str, optional
    defect_center : sequence of 3 floats, optional
        Fractional coordinates of the defect centre (stored in output only).

    Returns
    -------
    dict
        Serialisable result dictionary (spin → k-point → band → metrics).
    """
    n_kpoints = procar_data["n_kpoints"]
    n_bands = procar_data["n_bands"]
    n_ions = procar_data["n_ions"]
    spins = procar_data["spins"]
    site_proj = procar_data["site_proj"]  # {spin: (nk, nb, ni)}
    eigenvalues = procar_data.get("eigenvalues")
    occupancies = procar_data.get("occupancies")

    neighbor_arr = np.array(sorted(set(int(i) for i in neighbor_indices)), dtype=int)

    # Build a human-readable spin label mapping
    def _spin_label(spin, idx: int) -> str:
        # Works with pymatgen Spin objects and our _Spin sentinels
        try:
            from pymatgen.electronic_structure.core import Spin

            if spin == Spin.up:
                return "spin_1"
            if spin == Spin.down:
                return "spin_2"
        except ImportError:
            pass
        # Fallback: use the index
        return f"spin_{idx + 1}"

    data_out: PRatioData = {}

    for spin_idx, spin in enumerate(spins):
        sp_label = _spin_label(spin, spin_idx)
        proj = site_proj[spin]  # (nk, nb, ni)
        data_out[sp_label] = {}

        for ik in range(n_kpoints):
            kpt_label = f"kpt_{ik + 1}"
            data_out[sp_label][kpt_label] = {}

            for ib in range(n_bands):
                band_label = f"band_{ib + 1}"

                p_i = proj[ik, ib, :]  # (n_ions,)
                p_total = float(p_i.sum())

                if p_total > 1e-12:
                    p_neighbors = (
                        float(p_i[neighbor_arr].sum()) if neighbor_arr.size else 0.0
                    )
                    p_ratio = p_neighbors / p_total
                    ipr = float((p_i**2).sum()) / (p_total**2)
                else:
                    p_neighbors = 0.0
                    p_ratio = 0.0
                    ipr = 0.0

                energy = occ = None
                if eigenvalues is not None and spin in eigenvalues:
                    energy = float(eigenvalues[spin][ik, ib])
                if occupancies is not None and spin in occupancies:
                    occ = float(occupancies[spin][ik, ib])

                data_out[sp_label][kpt_label][band_label] = {
                    "energy": energy,
                    "occupation": occ,
                    "p_ratio": round(p_ratio, 8),
                    "ipr": round(ipr, 8),
                    "p_neighbors": round(p_neighbors, 8),
                    "p_total": round(p_total, 8),
                }

    return {
        "defect_name": defect_name,
        "defect_center": list(defect_center),
        "neighbor_atom_indices": neighbor_arr.tolist(),
        "n_atoms": n_ions,
        "n_spins": len(spins),
        "n_kpoints": n_kpoints,
        "n_bands": n_bands,
        "data": data_out,
    }


# ---------------------------------------------------------------------------
# High-level pipeline
# ---------------------------------------------------------------------------


class ParticipationRatioCalculator:
    """
    High-level calculator for electronic-state P-ratio and IPR.

    Orchestrates file reading, neighbour resolution, the core computation,
    and serialisation to JSON / CSV.

    Parameters
    ----------
    procar : str or Path
        Path to VASP PROCAR file.
    defect_entry : str or Path
        Path to ``defect_entry.json``.
    defect_structure_info : str or Path or None, optional
        Path to ``defect_structure_info.json``.  When supplied, neighbour
        indices are read directly from this file.
    poscar : str or Path or None, optional
        Path to POSCAR/CONTCAR used as fallback for neighbour search.
    cutoff_radius : float, optional
        Cutoff radius (Å) for the distance-based fallback neighbour search.
        Default: 3.5 Å.
    use_pymatgen : bool, optional
        Use pymatgen's Procar parser when available.  Default: ``True``.

    Examples
    --------
    >>> calc = ParticipationRatioCalculator(
    ...     procar="PROCAR",
    ...     defect_entry="defect_entry.json",
    ...     defect_structure_info="defect_structure_info.json",
    ... )
    >>> result = calc.run()
    >>> calc.to_json("participation_ratio.json")
    >>> calc.to_csv("participation_ratio.csv")
    """

    def __init__(
        self,
        procar: str | Path,
        defect_entry: str | Path,
        defect_structure_info: Optional[str | Path] = None,
        poscar: Optional[str | Path] = None,
        cutoff_radius: float = 3.5,
        use_pymatgen: bool = True,
    ) -> None:
        self.procar_path = Path(procar)
        self.defect_entry_path = Path(defect_entry)
        self.dsi_path = Path(defect_structure_info) if defect_structure_info else None
        self.poscar_path = Path(poscar) if poscar else None
        self.cutoff_radius = cutoff_radius
        self.use_pymatgen = use_pymatgen
        self._result: Optional[dict] = None

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _load_defect_entry(self) -> dict:
        if not self.defect_entry_path.exists():
            raise FileNotFoundError(
                f"defect_entry.json not found: {self.defect_entry_path}"
            )
        with open(self.defect_entry_path) as fh:
            data = json.load(fh)
        from defectpl.defect_utils import DEFECT_ENTRY_SCHEMA_VERSION

        file_ver = data.get("schema_version")
        if file_ver is not None and file_ver != DEFECT_ENTRY_SCHEMA_VERSION:
            import warnings

            warnings.warn(
                f"defect_entry.json has schema_version '{file_ver}' but "
                f"defectpl expects '{DEFECT_ENTRY_SCHEMA_VERSION}'. "
                "Results may be incorrect.",
                UserWarning,
                stacklevel=3,
            )
        return data

    def _find_poscar(self) -> Optional[Path]:
        """Return poscar_path if set; else probe common filenames near PROCAR."""
        if self.poscar_path is not None:
            return self.poscar_path
        parent = self.procar_path.parent
        for name in ("CONTCAR", "POSCAR"):
            p = parent / name
            if p.exists():
                return p
        return None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self) -> dict:
        """
        Execute the full P-ratio / IPR calculation pipeline.

        Returns
        -------
        dict
            Nested result dictionary (spin → k-point → band → metrics).
            The same object is also stored as ``self.result``.
        """
        # 1. Load defect metadata
        entry = self._load_defect_entry()
        defect_name = entry.get("name", entry.get("defect_name", "unknown"))
        defect_center = entry.get("defect_center", [0.5, 0.5, 0.5])

        # 2. Resolve neighbour atom indices
        poscar_path = self._find_poscar()
        neighbor_indices, neighbor_source = resolve_neighbors(
            dsi_path=self.dsi_path,
            poscar_path=poscar_path,
            defect_center_frac=defect_center,
            cutoff_radius=self.cutoff_radius,
        )
        logger.info("Neighbours resolved from: %s", neighbor_source)

        # 3. Parse PROCAR
        procar_data = read_procar(self.procar_path, use_pymatgen=self.use_pymatgen)
        logger.info(
            "PROCAR: %d spin(s), %d k-point(s), %d band(s), %d ions",
            procar_data["n_spins"],
            procar_data["n_kpoints"],
            procar_data["n_bands"],
            procar_data["n_ions"],
        )

        # 4. Compute metrics
        self._result = compute_participation_ratios(
            procar_data=procar_data,
            neighbor_indices=neighbor_indices,
            defect_name=defect_name,
            defect_center=defect_center,
        )
        self._result["neighbor_source"] = neighbor_source

        return self._result

    @property
    def result(self) -> Optional[dict]:
        """The computed result dictionary or None if :meth:`run` has not been called."""
        return self._result

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_json(self, path: str | Path) -> Path:
        """
        Serialise the result to a JSON file.

        Parameters
        ----------
        path : str or Path

        Returns
        -------
        Path  — the written file path.
        """
        if self._result is None:
            raise RuntimeError("Call run() before to_json()")
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as fh:
            json.dump(self._result, fh, indent=2)
        logger.info("JSON written: %s", path)
        return path

    def to_csv(self, path: str | Path) -> Path:
        """
        Write a flat CSV summary of all (spin, k-point, band) metrics.

        Columns: spin, kpt, band, energy, occ, p_ratio, ipr,
                 p_neighbors, p_total

        Parameters
        ----------
        path : str or Path

        Returns
        -------
        Path
        """
        import csv

        if self._result is None:
            raise RuntimeError("Call run() before to_csv()")

        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        fieldnames = [
            "spin",
            "kpt",
            "band",
            "energy",
            "occ",
            "p_ratio",
            "ipr",
            "p_neighbors",
            "p_total",
        ]
        rows = []
        for sp_label, kpt_dict in self._result["data"].items():
            spin_idx = int(sp_label.split("_")[1])
            for kpt_label, band_dict in kpt_dict.items():
                kpt_idx = int(kpt_label.split("_")[1])
                for band_label, vals in band_dict.items():
                    band_idx = int(band_label.split("_")[1])
                    rows.append(
                        {
                            "spin": spin_idx,
                            "kpt": kpt_idx,
                            "band": band_idx,
                            "energy": vals.get("energy"),
                            "occ": vals.get("occupation"),
                            "p_ratio": vals["p_ratio"],
                            "ipr": vals["ipr"],
                            "p_neighbors": vals["p_neighbors"],
                            "p_total": vals["p_total"],
                        }
                    )

        with open(path, "w", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)

        logger.info("CSV written: %s (%d rows)", path, len(rows))
        return path

    # ------------------------------------------------------------------
    # Convenience query
    # ------------------------------------------------------------------

    def top_localized(self, n: int = 10, metric: str = "p_ratio") -> List[dict]:
        """
        Return the *n* most localised states sorted by ``metric``.

        Parameters
        ----------
        n : int, optional (default 10)
        metric : {"p_ratio", "ipr"}, optional

        Returns
        -------
        list of dict, each with keys:
            spin, kpt, band, energy, occ, p_ratio, ipr
        """
        if self._result is None:
            raise RuntimeError("Call run() first.")

        rows = []
        for sp_label, kpt_dict in self._result["data"].items():
            for kpt_label, band_dict in kpt_dict.items():
                kpt_idx = int(kpt_label.split("_")[1])
                for band_label, vals in band_dict.items():
                    band_idx = int(band_label.split("_")[1])
                    rows.append(
                        dict(
                            spin=sp_label,
                            kpt=kpt_idx,
                            band=band_idx,
                            energy=vals.get("energy"),
                            occ=vals.get("occupation"),
                            p_ratio=vals["p_ratio"],
                            ipr=vals["ipr"],
                        )
                    )

        rows.sort(key=lambda x: -(x[metric] or 0))
        return rows[:n]


# ---------------------------------------------------------------------------
# Result helpers
# ---------------------------------------------------------------------------


def flatten_pr_result(result: dict, kpt_idx: int = 0) -> List[dict]:
    """
    Flatten the nested PR result dictionary into a list of per-band row dicts.

    Parameters
    ----------
    result : dict
        As returned by :func:`compute_participation_ratios` or loaded from
        ``participation_ratio.json``.
    kpt_idx : int, optional
        0-based k-point index to extract.  Default 0 (Gamma point).

    Returns
    -------
    list of dict
        Each dict has keys: ``spin``, ``band``, ``energy``, ``occ``,
        ``p_ratio``, ``ipr``, ``p_neighbors``, ``p_total``.
    """
    rows: List[dict] = []
    data = result.get("data", {})
    kpt_label = f"kpt_{kpt_idx + 1}"
    for sp_label, kpt_dict in data.items():
        if kpt_label not in kpt_dict:
            continue
        for band_label, vals in kpt_dict[kpt_label].items():
            band_idx = int(band_label.split("_")[1])
            rows.append(
                {
                    "spin": sp_label,
                    "band": band_idx,
                    "energy": vals.get("energy"),
                    "occ": vals.get("occupation", 0.0) or 0.0,
                    "p_ratio": vals.get("p_ratio", 0.0) or 0.0,
                    "ipr": vals.get("ipr", 0.0) or 0.0,
                    "p_neighbors": vals.get("p_neighbors", 0.0) or 0.0,
                    "p_total": vals.get("p_total", 0.0) or 0.0,
                }
            )
    return rows


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

_SPIN_COLORS = {"spin_1": "#1f77b4", "spin_2": "#d62728"}
_SPIN_SYMBOLS = {"spin_1": "spin ↑", "spin_2": "spin ↓"}
_METRIC_LABEL = {"p_ratio": "P-ratio", "ipr": "IPR"}


def _require_matplotlib() -> tuple:
    """Return (matplotlib, pyplot) or raise ImportError with install hint."""
    try:
        import matplotlib as mpl
        import matplotlib.pyplot as plt

        return mpl, plt
    except ImportError:
        raise ImportError(
            "matplotlib is required for PR plotting.  "
            "Install with:  pip install matplotlib"
        )


def _scatter_spin_rows(ax, rows: List[dict], metric: str, x_key: str) -> None:
    """Draw filled/open scatter markers per spin for a list of row dicts."""

    by_spin = {}
    for row in rows:
        by_spin.setdefault(row["spin"], []).append(row)

    for sp_label, sp_rows in sorted(by_spin.items()):
        color = _SPIN_COLORS.get(sp_label, "gray")
        sym = _SPIN_SYMBOLS.get(sp_label, sp_label)
        xs_occ, ys_occ = [], []
        xs_emp, ys_emp = [], []
        for row in sp_rows:
            x = row[x_key]
            y = row[metric]
            if x is None or y is None:
                continue
            if row["occ"] >= 0.5:
                xs_occ.append(x)
                ys_occ.append(y)
            else:
                xs_emp.append(x)
                ys_emp.append(y)

        kw = dict(marker="o", s=35, zorder=3)
        if xs_occ:
            ax.scatter(xs_occ, ys_occ, c=color, label=f"{sym} (occ)", **kw)
        if xs_emp:
            ax.scatter(
                xs_emp,
                ys_emp,
                facecolors="none",
                edgecolors=color,
                label=f"{sym} (empty)",
                **kw,
            )


def plot_pr_vs_energy(
    result: dict,
    metric: str = "p_ratio",
    threshold: float = 0.2,
    vbm: Optional[float] = None,
    cbm: Optional[float] = None,
    emin: Optional[float] = None,
    emax: Optional[float] = None,
    kpt_idx: int = 0,
    title: Optional[str] = None,
    out: Optional[str | Path] = None,
    ax=None,
    figsize: tuple = (8, 5),
    dpi: int = 150,
):
    """
    Scatter plot of P-ratio or IPR versus Kohn-Sham energy.

    Parameters
    ----------
    result : dict
        Nested PR result dict (from :func:`compute_participation_ratios` or
        loaded from ``participation_ratio.json``).
    metric : {"p_ratio", "ipr"}
        Quantity plotted on the Y-axis.
    threshold : float
        Horizontal dashed threshold reference line.  Default 0.2.
    vbm : float, optional
        Valence Band Maximum energy (eV).  Shown as a vertical orange line.
    cbm : float, optional
        Conduction Band Minimum energy (eV).  Shown as a vertical green line.
    emin : float, optional
        Lower energy boundary for filtering.
    emax : float, optional
        Upper energy boundary for filtering.
    kpt_idx : int
        0-based k-point index to use.  Default 0.
    title : str, optional
        Plot title.  Defaults to the defect name in *result*.
    out : str or Path, optional
        If given, save the figure to this path.
    ax : matplotlib.axes.Axes, optional
        Inject into an existing Axes.  When None a new figure is created.
    figsize : tuple
        Figure size (width, height) in inches.
    dpi : int
        Resolution when saving.

    Returns
    -------
    matplotlib.axes.Axes
    """
    _, plt = _require_matplotlib()

    rows = flatten_pr_result(result, kpt_idx=kpt_idx)
    if emin is not None:
        rows = [r for r in rows if r["energy"] is not None and r["energy"] >= emin]
    if emax is not None:
        rows = [r for r in rows if r["energy"] is not None and r["energy"] <= emax]

    standalone = ax is None
    if standalone:
        fig, ax = plt.subplots(figsize=figsize)

    _scatter_spin_rows(ax, rows, metric=metric, x_key="energy")

    ax.axhline(
        threshold,
        color="gray",
        linestyle="--",
        linewidth=1,
        label=f"threshold = {threshold}",
    )

    if vbm is not None:
        ax.axvline(
            vbm,
            color="orange",
            linestyle=":",
            linewidth=1.2,
            label=f"VBM = {vbm:.3f} eV",
        )
    if cbm is not None:
        ax.axvline(
            cbm,
            color="green",
            linestyle=":",
            linewidth=1.2,
            label=f"CBM = {cbm:.3f} eV",
        )

    ax.set_xlabel("Energy (eV)")
    ax.set_ylabel(_METRIC_LABEL.get(metric, metric))
    ax.set_title(title or result.get("defect_name", "defect"))
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    if standalone and out is not None:
        ax.get_figure().tight_layout()
        ax.get_figure().savefig(str(out), dpi=dpi, bbox_inches="tight")
        plt.close(ax.get_figure())

    return ax


def plot_pr_vs_band_index(
    result: dict,
    metric: str = "p_ratio",
    threshold: float = 0.2,
    emin: Optional[float] = None,
    emax: Optional[float] = None,
    kpt_idx: int = 0,
    title: Optional[str] = None,
    out: Optional[str | Path] = None,
    ax=None,
    figsize: tuple = (10, 5),
    dpi: int = 150,
):
    """
    Scatter plot of P-ratio or IPR versus band index.

    Band indices match the VASP band numbering (1-based).  Separate spin
    channels are drawn in different colours; filled markers denote occupied
    states, open markers denote empty states.

    Parameters
    ----------
    result : dict
        Nested PR result dict.
    metric : {"p_ratio", "ipr"}
        Quantity plotted on the Y-axis.
    threshold : float
        Horizontal dashed threshold reference line.  Default 0.2.
    emin : float, optional
        Restrict displayed bands to those with energy ≥ emin (eV).
    emax : float, optional
        Restrict displayed bands to those with energy ≤ emax (eV).
    kpt_idx : int
        0-based k-point index to use.  Default 0.
    title : str, optional
        Plot title.  Defaults to the defect name in *result*.
    out : str or Path, optional
        If given, save the figure to this path.
    ax : matplotlib.axes.Axes, optional
        Inject into an existing Axes.
    figsize : tuple
        Figure size in inches.
    dpi : int
        Resolution when saving.

    Returns
    -------
    matplotlib.axes.Axes
    """
    _, plt = _require_matplotlib()

    rows = flatten_pr_result(result, kpt_idx=kpt_idx)
    if emin is not None:
        rows = [r for r in rows if r["energy"] is not None and r["energy"] >= emin]
    if emax is not None:
        rows = [r for r in rows if r["energy"] is not None and r["energy"] <= emax]

    standalone = ax is None
    if standalone:
        fig, ax = plt.subplots(figsize=figsize)

    _scatter_spin_rows(ax, rows, metric=metric, x_key="band")

    ax.axhline(
        threshold,
        color="gray",
        linestyle="--",
        linewidth=1,
        label=f"threshold = {threshold}",
    )

    ax.set_xlabel("Band index")
    ax.set_ylabel(_METRIC_LABEL.get(metric, metric))
    ax.set_title(title or result.get("defect_name", "defect"))
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    if standalone and out is not None:
        ax.get_figure().tight_layout()
        ax.get_figure().savefig(str(out), dpi=dpi, bbox_inches="tight")
        plt.close(ax.get_figure())

    return ax
